# Here lie dragons!

name: Build Paper
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.3.5
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2.3.1
              with:
                  java-version: ${{ matrix.java }}
                  cache: "gradle"
                  distribution: "temurin"
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew createReobfBundlerJar --stacktrace
                  mv build/libs/*.jar paper-turna-$GITHUB_RUN_NUMBER.jar
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2.2.4
              with:
                  name: PaperSpigot-TurnA-${{ github.run_number }}
                  path: paper-turna-${{ github.run_number }}.jar
